### ISSUE TITLE
Hard error when attempting upgrade flow

### ISSUE THREAD

**Issue by davidkarlsen** [kubeapps/kubeapps#1468]
### Description:

When I go to app, click on upgrade, I get "Sorry! Something went wrong."
### Steps to reproduce the issue:

1. select namespace with dropdown
2. click applications tab
3. click upgrade
4. it fails

### Describe the results you received:

See log in bottom

### Describe the results you expected:

Should be able to upgrade app.

### Additional information you deem important (e.g. issue happens only occasionally):

Error happens consistently.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3+icp", GitCommit:"", GitTreeState:""}```

- Output of `helm list <kubeapps-release-name>`:

```
kubeapps        32              Fri Dec 20 16:53:06 2019        DEPLOYED        kubeapps-3.2.3  v1.7.2          kubeapps 
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9+icp-ee", GitCommit:"fccfecc454d446967475ce34d13d3d63d407bf09", GitTreeState:"clean", BuildDate:"2019-08-27T08:46:50Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}```

### Browser-log

```
react-dom.production.min.js:196 YAMLSemanticError: Map keys must be unique; "name" is repeated
    at Object.t.default [as resolve] (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:533068)
    at e.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:355401)
    at e.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:355775)
    at t.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1486271)
    at https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:536736
    at Object.t.default [as resolve] (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:536938)
    at e.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:355401)
    at e.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:355775)
    at t.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1486271)
    at https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:531683
    at Object.t.default [as resolve] (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:532331)
    at e.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:355401)
    at e.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:355775)
    at t.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1486271)
    at https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1481752
    at Array.forEach (<anonymous>)
    at t.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1481602)
    at t.value (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1480354)
    at m (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1455684)
    at Object.parse (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1456175)
    at t.componentDidUpdate (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:2307633)
    at https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1124219
    at t.unstable_runWithPriority (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1143550)
    at Vi (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1068317)
    at Tu (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1120513)
    at gu (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1110811)
    at https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1068607
    at t.unstable_runWithPriority (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1143550)
    at Vi (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1068317)
    at Yi (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1068553)
    at Gi (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1068488)
    at du (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1107379)
    at Object.enqueueSetState (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1073310)
    at u.w.setState (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1017833)
    at u.l.onStateChange (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:412963)
    at Object.notify (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1179340)
    at e.t.notifyNestedSubs (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1178976)
    at u.l.onStateChange (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:412981)
    at Object.notify (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1179340)
    at e.t.notifyNestedSubs (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1178976)
    at u.l.onStateChange (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:412981)
    at Object.notify (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1179340)
    at e.t.notifyNestedSubs (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1178976)
    at u.l.onStateChange (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:412981)
    at Object.notify (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1179340)
    at e.t.notifyNestedSubs (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1178976)
    at u.l.onStateChange (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:412981)
    at v (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:264442)
    at https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:1193977
    at https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:2012326
    at dispatch (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:267824)
    at Object.<anonymous> (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:548980)
    at https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:551079
    at Object.next (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:551184)
    at a (https://kubeapps-global.finods.com/static/js/main.64ae6790.js:1:549889)
ds @ react-dom.production.min.js:196
```

**Comment by andresmgot** [comment]
It seems like a network issue. Can you send a screenshot of the Network tab of the Browser console?

Also, are all the components of Kubeapps healthy? (you can check that executing `kubectl get pods -n kubeapps`)

**Comment by davidkarlsen** [comment]
They are healthy and no errors in the logs. I had to delete the installed app and reinstall it. From the error YAMLSemanticError: Map keys must be unique; " it seems to not like the existing values that were stored.

**Comment by andresmgot** [comment]
Yes, I have seen that error before, when the service that return the app info or the chart is down so the response is empty (but your issue may be different). You are no longer seeing the error?

**Comment by davidkarlsen** [comment]
Not after deleting the app and reinstalling it (the business app - not kubeapps). I do not believe this to be infra error as:
* it happened consistently
* other apps could be upgraded
* it was able to pull the existing values to display them r/o on the app page

Maybe yaml-parsing errors could be handled in the ui - worst case scenario could show the page for upgrade without existing values. The the user can still install and avoid downtime by uninstall/install cycle

**Comment by andresmgot** [comment]
I agree in case it's a YAML parsing error but we would need to be able to reproduce it in order to verify we can fix the bug. Let us know if you find the way to reproduce it.

**Comment by cscazorla** [comment]
@davidkarlsen , we're closing this ticket. Let us know if you keep facing the issue.
