### ISSUE TITLE
Upgrading an application gives an error when AppRepository is not on namespace

### ISSUE THREAD

**Issue by alexandredantas** [kubeapps/kubeapps#1985]
### Description:

After installing an application, I tried to perform an upgrade but got an error because app repositories are only set up on the Kubeapps namespace.

### Steps to reproduce the issue:

1. Make sure App Repositories are only global (registered through All namespaces only)
2. Select a namespace other than Kubeapps namespace
3. Install an application in any version
4. After install, perform an upgrade
5. Upgrade will not happen due to an error

### Describe the results you received:

Upgrade was unsuccessful due to an error shown on screen.

### Describe the results you expected:

Because install was ok, even without the app repository I expected the upgrade should work too.

### Additional information you deem important (e.g. issue happens only occasionally):

If repository where the application came from is set up on namespace, upgrade works fine.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
```

- Output of `helm list <kubeapps-release-name>`:

```
NAME   	REVISION	UPDATED                 	STATUS  	CHART                  	APP VERSION	NAMESPACE 
wry-fog	3       	Fri Aug 28 20:26:40 2020	DEPLOYED	app-beakman-test-0.0.68	1.0        	dev-rubens
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

- Error log:

```
PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 138948 [running]:
github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x7f82dee230a8, 0xc0035d7308, 0xc0001b3a40, 0xc003fcf900)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/recovery.go:159 +0xcb
panic(0x14830a0, 0x22d6a70)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeapps/kubeapps/cmd/tiller-proxy/internal/handler.(*TillerProxy).UpgradeRelease(0xc0003210b0, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcfb00, 0xc0042db380)
	/go/src/github.com/kubeapps/kubeapps/cmd/tiller-proxy/internal/handler/handler.go:142 +0xac
github.com/kubeapps/kubeapps/cmd/tiller-proxy/internal/handler.(*TillerProxy).OperateRelease(0xc0003210b0, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcfb00, 0xc0042db380)
	/go/src/github.com/kubeapps/kubeapps/cmd/tiller-proxy/internal/handler/handler.go:100 +0xcb
github.com/kubeapps/kubeapps/pkg/handlerutil.WithParams.ServeHTTP(0xc0003276f0, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcfb00)
	/go/src/github.com/kubeapps/kubeapps/pkg/handlerutil/handlerutil.go:22 +0x5c
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000272000, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcf900)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/urfave/negroni.Wrap.func1(0x7f82dee230a8, 0xc0035d7308, 0xc003fcf900, 0xc0042df240)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc00000c540, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcf900, 0xc0042df240)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x1828f80, 0xc00000c540, 0xc00000c5c0, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcf900)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Static).ServeHTTP(0xc0000b62d0, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcf900, 0xc0042df220)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/static.go:34 +0x7ba
github.com/urfave/negroni.middleware.ServeHTTP(0x1827580, 0xc0000b62d0, 0xc00000c5a0, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcf900)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Logger).ServeHTTP(0xc0003cdb90, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcf900, 0xc0042df200)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/logger.go:62 +0x8e
github.com/urfave/negroni.middleware.ServeHTTP(0x1827520, 0xc0003cdb90, 0xc00000c580, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcf900)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc0001b3a40, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcf900, 0xc0042df1e0)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/recovery.go:193 +0xae
github.com/urfave/negroni.middleware.ServeHTTP(0x1827560, 0xc0001b3a40, 0xc00000c560, 0x7f82dee230a8, 0xc0035d7308, 0xc003fcf900)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0000b6360, 0x185a820, 0xc0039a8ee0, 0xc003fcf900)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96 +0xeb
net/http.serverHandler.ServeHTTP(0xc0001d42a0, 0x185a820, 0xc0039a8ee0, 0xc003fcf900)
	/usr/local/go/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc004234500, 0x185eea0, 0xc0040b0b00)
	/usr/local/go/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2957 +0x384
```

**Comment by andresmgot** [comment]
Thanks for reporting the issue @alexandredantas! We are aware of it and we have just merged a fix (more info here: https://github.com/kubeapps/kubeapps/issues/1980).

**Comment by absoludity** [comment]
Thanks for the report. The actual issue (unable to upgrade) is fixed in the PR attached to #1980 as Andres mentioned, but you also pointed out that this issue is not handled correctly in the tiller-proxy backend (nil pointer de-reference), so I've fixed that in #1988.

**Comment by alexandredantas** [comment]
@andresmgot @absoludity thank you very much for your response! Should I close the issue now?

**Comment by absoludity** [comment]
It will close automatically when the above PR lands. Thanks.
